@extends('layouts.home')
@section('title',"Inicio - Let's Van")
@section('main')
<div class="container text-justify privacidad">
    <h2 class="text-center my-5">Términos y Condiciones Generales de Uso de Plataforma</h2>
    <p class="text-right my-5">31 de Agosto de 2021</p>
    <div>
        <p>
            LET’S VAN Es una agencia de viajes On Line, que por medio de la plataforma web. wwww.letsvan.com.mx, se
            encarga de enlazar pasajeros y armar un “Team Travel, de punto a punto. Esto con la finalidad de viajar a un
            bajo costo, para lo cual se apoya de contratar el servicio de transporte turistico con placas federales y
            que cuentan con los permisos necesarios de turismo para trasladar grupos de un destino a otro, con seguro de
            cobertura amplia y responsabilidad civil, adicinal que cuentan con toda la documentación para la realización
            de los viajes turisticos. Por lo que al aceptar los terminos y condiciones generales de la plataforma,
            deslinda de responsabilidad a Let’s Van, así como a sus propietarios y empleados de cualquier
            responsabilidad civil que sucediera por la prestación del servicio y esta será asumida por la aseguradora
            vigente.
        </p>
    </div>
    <div class="mt-4">
        <h4 class="counter">CONTRATACIÓN</h4>
        <p>
            Los servicios los pueden contratar las 24 horas mediante la plataforma web. www.letsvan.com.mx o bien vía
            telefonica con la agencia al Tel. 4434489901 y al 5529978451 en un horario de 8:00 am a 10:00 pm 
        </p>
        <p>        
            Los presentes Términos y Condiciones se encuentran dirigidos a los Usuarios que residan o se encuentren
            físicamente en el territorio de los Estados Unidos Mexicanos (“México”). Aquellos Usuarios que residan o se
            encuentren en cualquier otro lugar y que decidan acceder y/o utilizar los Servicios lo harán bajo su propia
            responsabilidad y riesgo, debiéndose asegurar de que tal acceso y/o utilización cumple con la legislación
            local aplicable, acordando someterse a estos Términos y Condiciones y a las leyes aplicables en la Ciudad de
            México, México, renunciando a cualquier otra legislación o fuero, que por razón de su nacionalidad,
            domicilio o por cualquier otra razón pudiere llegar a corresponderles.
        </p>
        <p>
            Serán referidos como “Usuarios” y/o “Pasajeros” todas las personas físicas que se registren en la
            “Plataforma” a la que se hace referencia en la sección VII del presente instrumento y/o accedan a los Medios
            físicos o digitales a través de cualquier dispositivo u ordenador, sin importar que dicho acceso se realice
            por conducto de la Aplicación o el Sitio Web, así como quienes utilicen regular u ocasionalmente el
            Servicio.
        </p>
        <p>
            Los presentes Términos y Condiciones están destinados y dirigidos a regular las condiciones de registro,
            afiliación, acceso, uso y aprovechamiento de la Plataforma, los Medios Digitales y los Servicios. El uso
            directo o indirecto de la Plataforma, y de cualquiera de los Medios Físicos o Digitales o los Servicios por
            parte de los Usuarios presupone e implica la aceptación expresa y plena de todas y cada una de las
            disposiciones contenidas y previstas en los presentes Términos y Condiciones, así como la sujeción
            correspondiente a los mismos. Los Usuarios reconocen que es su obligación consultar y comprender el
            contenido de los Términos y Condiciones, así como de las modificaciones realizadas de tiempo en tiempo a los
            presentes, antes de acceder y utilizar los Medios Físicos o Digitales, los Servicios, realizar Reservas, o
            Comprar boletos de Viajes.
        </p>
        <p>
            Será responsabilidad única y exclusiva de los Usuarios leer, comprender y aceptar las disposiciones
            contenidas en los presentes Términos y Condiciones, así como en el Aviso de Privacidad que se encuentra a su
            disposición en el Sitio Web, en la Aplicación y en los puntos físicos de venta.
        </p>
        <p>
            En caso de que los Usuarios por cualquier motivo no deseen obligarse en los exactos Términos y Condiciones
            establecidos en el presente Contrato, o de no estar conformes con la totalidad o una parte de las
            previsiones aquí contenidas, deberán abstenerse de realizar cualquier registro y de utilizar los Medios
            Físicos o Medios Digitales y, en su caso, de solicitar Reservas, o participar en Viajes, además de abandonar
            inmediatamente cualquier Medio Digital que se encuentren utilizando o que hayan utilizado o donde se hayan
            registrado; bajo el entendido de que al utilizar el Sitio Web o la Aplicación Móvil, o acceder a los
            Servicios a través de puntos de venta físicos, aceptan plenamente el contenido de los Términos y Condiciones
            establecidos en el presente Contrato y se obligan conforme a éste.
        </p>
    </div>
    <div class="mt-4">
        <h4 class="counter">DEFINICIONES.</h4>
        <p>Para mejor claridad de lo expresado en el presente instrumento, utilizaremos términos definidos. Los términos que aparezcan en mayúsculas, a los que no se les haya atribuido un significado distinto en diversas secciones del presente documento, serán entendidos de la siguiente manera: </p>
        <p>“Agregador Bancario” se refiere a la o las empresas especializadas que han sido contratadas por Let’s Van para procesar los pagos realizados con tarjeta bancaria u otros medios de pago electrónicos que realizan los Usuarios como contraprestación por los Viajes.</p>
        <p>“Aliados” se refiere a los Transportistas Independientes quienes son los permisionarios, ya sea  personas físicas o morales que sean propietarias y/o legítimas poseedoras de las unidades de autobuses o cualquier otro vehículo,  mismas que prestan directamente a los Usuarios el servicio de transporte independiente y que cuenten con los permisos expedidos por las autoridades correspondientes conforme a la normativa vigente.</p>
        <p>“Cargos Adicionales” se refiere conjuntamente a las Penalizaciones, cancelaciones, así como a cualesquier costos o importes accesorios o complementarios que deban ser cargados al Medio de Pago autorizado por el Usuario.</p>
        <p>“Centro de Atención y Soporte Telefónico”: El área dedicada a la comunicación vía telefónica ya sea de manera entrante o saliente con los usuarios, socios comerciales, compañías asociadas, entre otros, gestionado por personal especializado con los recursos físicos y tecnológicos necesarios, basados en procesos y procedimientos definidos para atender las necesidades del usuario. El número para comunicarse al Centro de Atención y Soporte Telefónico es el que se indica en los presentes Términos y Condiciones.</p>
        <p>“Centro de Atención y Soporte WhatsApp”: El área dedicada a la comunicación vía WhatsApp ya sea de manera entrante o saliente con los usuarios, socios comerciales, compañías asociadas, entre otros, gestionado por personal especializado con los recursos físicos y tecnológicos necesarios, basados en procesos y procedimientos definidos para atender las necesidades del usuario. El número para comunicarse al Centro de Atención y Soporte WhatsApp es el que se indica en los presentes Términos y Condiciones.</p>
        <p>“Compra” se refiere al pago que realiza el Usuario de su boleto, con lo cual asegura un asiento en una Unidad asignada específicamente a un Viaje.</p>
        <p>“Conductores” se refiere a las personas físicas que se encuentran directamente contratadas por los permisionarios quienes son los transportistas independientes y que se encargan de conducir de las Unidades de los Transportistas Independientes, o bien, las personas físicas por su propia cuenta fungen como los Transportistas Independientes. También se les hace referencia a los conductores como operadores.</p>
        <p>“Descuentos Permitidos” se refiere a las deducciones o abonos a que tenga derecho el Usuario que sean compensables frente a las Tarifas, con base en promociones, cupones digitales y/o códigos promocionales autorizados por Let’s Van en la Plataforma.</p>
        <p>Horario de Partida” se refiere a la hora exacta en la que el Trayecto partirá del Punto de Let’s Van de origen seleccionado por el Usuario.</p>
        <p>“Medios de Pago” se refiere a las tarjetas de débito, tarjetas de crédito, medios de pago electrónico y tarjetas de servicios que sean aceptadas por la Plataforma, así como al dinero en efectivo o cualquier otro medio para cubrir la Tarifa.</p>
        <p>“Normatividad Aplicable” se refiere a cualesquier códigos, leyes, reglamentos, decretos, acuerdos, circulares, bandos, lineamientos, disposiciones de carácter general y cualesquier normas jurídicas que sean aplicables al objeto del presente Contrato o de la sección específica donde se haga mención del presente término.</p>
        <p>“Número de Reservación” es el código alfanumérico personal e intransferible que la Plataforma otorga al Usuario al momento de realizar una Reserva y/o Compra y que, de manera conjunta a una identificación oficial del Usuario, servirá para identificar a éste último al momento de abordar una Unidad.</p>
        <p>“Penalizaciones” tiene el significado que se le atribuye en la sección XII del presente documento.</p>
        <p>“Plataforma”: es una herramienta digital de intermediación entre los Usuarios y los Aliados, por medio del cual los Usuarios realizan Reservas y/o Compras de Viajes, a la cual acceden a través de los Medios Digitales.</p>
        <p>“Punto de Destino Let’s Van en adelante Puntos Let’s Van” se refiere a la ubicación específica o a la coordenada geográfica exacta que el Trayecto señala como punto de salida o llegada de una Viaje.</p>
        <p>“Punto de Origen Let’s Van en adelante Puntos Let’s Van” se refiere a la ubicación específica del punto Let’s Van cuya coordenada geográfica exacta que el Trayecto señala como punto de inicio de un Viaje.</p>
        <p>“Punto Let’s Van”: se refiere a la ubicación específica o coordenada geográfica exacta que el trayecto señale como Punto de Origen (salida), y Punto de Destino (llegada) de un Viaje,</p>
        <p>“Servicio”: Se refiere a la intermediación que lleva a cabo Let’s Van, a través de la Plataforma, y los Medios Físicos y Digitales, para la reserva y/o adquisición por parte de los Usuarios, de boletos para viajes de autotransporte federal de pasajeros que realizan los permisionarios (Aliados).</p>
        <p>“Reserva”: se refiere a la solicitud que realiza el Usuario para apartar un asiento en una Unidad asignada específicamente a un Viaje.</p>
        <p>“Tarifa”: Monto establecido según los máximos permitidos por la Secretaría de Comunicaciones y Transportes, para la prestación de los servidores de los Aliados, para la venta de boletos individuales. </p>
        <p>“Trayectos”: se refiere a las rutas cuyos Puntos Let’s Van de Origen y Destino, y Horarios de Partida y Arribo se encuentran publicados en la Plataforma, con la finalidad de que los Usuarios reserven asientos en las Unidades y sean trasladados por los Operadores. Los Trayectos podrán tener paradas intermedias, mismas que se considerarán como Punto de Let’s Van de para los Usuarios que accedan a las Unidades en dichas ubicaciones.</p>
        <p>“Unidad” se refiere al vehículo automotor que es conducido por los Operadores y cuya propiedad o legítima posesión corresponde a los Transportistas Independientes.</p>
        <p>“Viaje” se refiere al traslado que realiza un Aliado en favor de un Usuario, desde el Punto Let’s Van de origen hasta el Punto Let’s Van de destino. Además del término “Viaje” para referirse a los traslados aquí señalados, también se les podrá denominar como “boleto” en el contenido del presente instrumento.</p>
        <p>Los términos definidos anteriormente podrán ser utilizados a lo largo del presente documento, indistintamente, en singular o en plural; en masculino, en femenino o en neutro; en mayúsculas o en minúsculas; sin que dicha utilización modifique su significado. En caso de que a los términos definidos en la presente sección se les haya atribuido un significado explicativo en otras secciones del presente documento, ambos significados se leerán e interpretarán conjuntamente. Los términos definidos exclusivamente en diversas secciones del presente instrumento tendrán los significados que ahí se les atribuye.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">SERVICIOS.</h4>
        <p>Let’s Van, a través de los Medios Físicos y Digitales, presta al Usuario el servicio de intermediación para la reserva y/o adquisición de boletos para viajes punto a punto prestado por los aliados permisionarios, a través de la Plataforma que pone a disposición de los Usuarios, a tales fines.</p>
        <p>Let’s Van, a través de los Medios Físicos o Digitales, pone a disposición de los Usuarios una Plataforma que permite la Reserva y/o Compra de boletos de Viajes con nuestros Aliados. Los Viajes serán prestados por Aliados (Transportistas Independientes) que cuentan con los permisos necesarios para la prestación de dichos servicios.</p>
        <p>Los Aliados son los únicos responsables por la prestación de los servicios de transporte independiente (autotransporte federal de pasajeros). Por lo anterior, el Usuario reconoce que Let’s Van actúa en calidad de intermediario entre el Usuario y el Aliado, y que Let’s Van no presta servicio de transporte alguno.</p>
        <p>Asimismo, el Usuario reconoce que los Conductores no son trabajadores de Let’s Van, por lo que será responsabilidad exclusiva de los Aliados y de los Conductores la prestación de los servicios de autotransporte federal de pasajeros que sean contratados a través de la Plataforma.</p>
        <p>El Usuario reconoce que los Aliados podrán contar con sus propias políticas de privacidad y condiciones generales de servicio o de contratación, por lo que, de ser el caso, el Usuario deberá consultar y aceptar, según corresponda, dichas políticas o condiciones, con independencia de lo previsto en este instrumento.</p>
        <h5><u>Contingencia sanitaria COVID</u></h5>
        <p>En cumplimiento con la circular obligatoria CO.DGAF-MED PREV.1/2020, “QUE ESTABLECE EL PLAN DE CONTINGENCIA DE AUTOTRANSPORTE FEDERAL ANTE EVENTOS DE IMPORTANCIA EN SALUD PÚBLICA” emitida por la Secretaría de Comunicaciones y Transportes, será obligatorio el uso de cubrebocas durante el ascenso, descenso y durante el trayecto total del viaje. Si el usuario hiciere caso omiso a las indicaciones del uso de cubrebocas de la manera adecuada, se le podrá negar el ascenso al autobús, o bien, se le podrá requerir que abandone el mismo.</p>
        <p>De igual manera si el usuario hace caso omiso de portar en todo momento el cubrebocas hasta llegar al punto Let’s Van de destino, aun con las indicaciones del embajador, se le podrá restringir la posibilidad de realizar una nueva compra o reserva. </p>
        <p>SEGURO DE VIAJERO.- El Aliado (permisionario), mismo que se muestra y específica en el boleto electrónico o físico al momento de la compra, será el obligado a brindar el seguro de viajero a los usuarios. El boleto fungirá como el seguro del viajero relacionado directamente con la prestación del servicio.</p>
        <p>En caso de producirse algún incidente o siniestro durante el viaje, el Aliado será el único responsable del mismo frente al Usuario, debido a que es su obligación brindarle el seguro de viaje, ya que es el permisionario encargado de la ruta. En tal sentido, es del conocimiento del Usuario que no es obligación de Let’s Van brindar un seguro de viaje, y por consiguiente, el Usuario acepta que no ejercerá reclamación alguna en contra de Let’s Van, y que de intentarlo, tal reclamación será improcedente. Que bajo ninguna circunstancia Let’s Van ni en ningún momento procederá en contra de Let’s Van reclamación alguna, debido a que no es el prestador del servicio y no está obligado a brindar el seguro de viaje.</p>
        <p>Let’s Van no quedará obligado frente a ningún usuario ni será responsable en ningún momento, ni tendrá obligación alguna en caso de algún incidente médico en el trayecto de la ruta, cualquier tema relacionado al seguro se tendrá que ver directamente con el Aliado (permisionario) encargado de la ruta en la que se suscite el incidente. </p>
        <p>Alergias/Venta a bordo: Durante todos los viajes se ofrece un servicio de venta de productos a bordo, entre los cuales podrán encontrarse, de manera enunciativa y no limitativa, los siguientes: cacahuates, chocolates, lácteos, entre otros; siendo de exclusiva responsabilidad del Usuario verificar el (los) contenido(s) de los productos que consuma.</p>
        <p>Ni Let’s Van ni los Aliados, se harán de ninguna manera  responsables por las reacciones alérgicas o de cualquier otra índole, que el Pasajero sufra o pueda llegar a sufrir como consecuencia directa del consumo de dichos productos vendidos a bordo.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">OBLIGACIONES DE LOS USUARIOS.</h4>
        <p>Información proporcionada en los procesos de reservación y/o compra.- Serán nulas automáticamente y no tendrán derecho a ninguna bonificación y/o cancelación los usuarios que realicen una reservación y/o compra a través de los medios digitales y/o por teléfono, con información falsa ya sea nombre, correo electrónico, formas de pago o cualquier otra información que sea necesaria para la reservación y/o compra, de igual manera Let’s Van se reserva el derecho a bloquear al Usuarios que realice reservas y/o compras con datos falsos.  </p>
        <p>Traslados.- Los Usuarios deberán trasladarse por sus propios medios a los Punto Let’s Van  de Partida donde se ubiquen las unidades de los Aliados, deberán presentarse con un mínimo de 15 minutos de anticipación en los puntos Let’s Van de partida, para revisión de documentos obligatorios: número de reservación de compra digital e identificación oficial vigente; en caso de documentar equipaje se deberán presentar con 25 minutos de anticipación a la hora de salida marcada en su boleto. En caso de que el Usuario no se presentare en los tiempos de anticipación establecidos en el presente instrumento, no se le permitirá el abordaje.</p>
        <p>Notificaciones de cambios operativos.- Los usuarios están obligados a proporcionar un número de teléfono celular y correo electrónico, para hacerles llegar, ya sea a través de mensajes de texto, notificación push, mensajes de whatsapp, o llamada telefónica, información sobre cambios en el itinerario de su viaje, cambios operativos en los puntos Let’s Van de origen o destino, así como cualquier cambio que Let’s Van o el Aliado decidan implementar a fin de garantizar la correcta operación. Dichas notificaciones se harán con 2 (dos) horas de anticipación a los horarios señalados en su boleto. </p>
        <p>Será total y plena responsabilidad del usuario el atender a las notificaciones antes mencionadas, para estar al tanto de los cambios que se le deban informar. Let’s Van no se hace responsable de las situaciones que deriven de la desatención del usuario, es decir, si el usuario no atiende a la información e instrucciones de cambios comunicados por Let’s Van, por lo que de ninguna manera Let’s Van estará obligado a realizar cualquier tipo de compensación, devolución, cambio o reintegro al usuario, resultado de la omisión del usuario. </p>
        <p><strong>Acreditación del pago.-</strong> Es obligación de los Usuarios pagar la Tarifa por cualquier medio autorizado establecido por Let’s Van antes de abordar una Unidad de los Aliados, así como conservar, resguardar, memorizar y proteger el Número de Reservación, y exhibir dicho Número de Reservación antes de abordar una Unidad.</p>
        <p><strong>Ascenso y Descenso.-</strong> Es obligación de los usuarios permanecer en la Unidad durante el trayecto del viaje, y realizar los ascensos y descensos únicamente en los Puntos Let’s Van de Origen y Destino establecidos en su reservación y boleto; toda vez que no están permitidos los ascensos y descensos en lugares distintos a los señalados.</p>
        <p>Por ningún motivo y con el objetivo de proveer la mayor seguridad y comodidad posible para los usuarios no se tendrá permitido hacer ascenso o descenso en puntos distintos a los marcados en su reservación y/o compra, por seguridad de los usuarios y de aquellos que se encuentren a bordo. </p>
        <p><strong>Limpieza especial.-</strong> El usuario que durante el viaje, tenga malestar estomacal o náuseas, deberán hacerlo del conocimiento del conductor, para poder proporcionarles la ayuda necesaria. </p>
        <p>Si el usuario no comunicare al conductor acerca de su malestar, no solicitare la ayuda del embajador y que como consecuencia de esta omisión genere un incidente  en cualquier parte del autobús y éste quedare inhabilitado (ya sea en el baño, asientos, cabinas, en otros), se le impondrá un el cargo de $400.00 (cuatrocientos pesos con 00/100 MXN) por concepto de limpieza especial.</p>
        <p>La cual se cobrará con el mismo método de pago que haya hecho su compra, si fuere con tarjeta de crédito/débito el pago se cargará automáticamente a la misma cuenta con la que realizó el pago. Si el usuario se niega a realizar dicho pago por limpieza se le podrán negar compras futuras.  </p>
        <p><strong>Viajando con menores.-</strong> Los menores de edad siempre deben viajar en compañía de un adulto, quien en todo momento será responsable de éste, presentará para la compra del boleto y del abordaje, los siguientes documentos originales: el acta de nacimiento, impresión a color de su CURP o pasaporte del menor original vigente; y la credencial escolar emitida por alguna Institución Educativa, en original.</p>
        <p>Si el niño está en el límite de edad (12 años), se debe presentar un documento oficial en original que acredite su edad (acta de nacimiento, impresión a color de su CURP o pasaporte original vigente; y credencial escolar en original).</p>
        <p>Los niños menores de 3 años cumplidos no pagan boleto, y viajarán en el mismo asiento del adulto que lo acompaña (un niño por adulto).</p>
        <p>Los usuarios a partir de los 13 años viajarán con boleto a precio de adulto.</p>
        <p>En el caso de un menor de edad acompañado de un Adulto que no fuera uno de sus padres o tutores, el responsable de dicho menor de edad deberá presentar el consentimiento dado por escrito y firmado por ambos padres o tutores legales, así como copia fotostática de las Identificaciones Oficiales de éstos últimos.</p>
        <p>Los menores de edad que no viajen en compañía de un adulto responsable por ellos, que acredite la documentación mencionada, no podrán realizar el ascenso y abordaje al autobús. </p>
        <p><strong>Seguridad.-</strong> Los usuarios, incluyendo los que viajen con menores de edad, deberán permanecer durante todo el trayecto en sus asientos, hasta finalizar el mismo, a  excepción de cuando usen el sanitario. </p>
        <p>Todos los usuarios sin excepción alguna, antes de iniciar el viaje deberán colocarse su cinturón de seguridad, que deberán mantenerlo puesto hasta finalizar su viaje y llegar al Punto Let’s Van. </p>
        <p>El usuario no deberá en ningún momento distraer al conductor o acceder al área de cabina. </p>
        <p>Los usuarios estarán obligados a seguir las instrucciones del personal de Let’s Van, en caso de presentarse algún incidente.</p>
        <p>Queda prohibido fumar cigarrillos y/o tabaco, así como utilizar cualquier tipo de vaporizadores, o cigarro electrónico en el interior de la unidad. En caso de hacer usos de los mismos, el usuario será acreedor a una multa por $7,500.00 (siete mil quinientos pesos 00/100), la cual se deberá cobrar al usuario al mismo método de pago que proporcionó para la compra de su boleto, de haber realizado el pago en efectivo, el cobro será en efectivo antes de realizar el descenso en el Punto Let’s Van de llegada.</p>
        <p><strong>Conducta.-</strong> Los Usuarios deberán respetar los deberes generales de conducta previstos en los presentes Términos y Condiciones.</p>
        <p>Los Usuarios tienen el deber fundamental de tratar a los Conductores y a tratarse entre ellos con respeto, dignidad, cordialidad y reciprocidad. Además, los Usuarios deberán proteger recíprocamente sus condiciones de seguridad personal, así como sus pertenencias.</p>
        <p>Por lo tanto, de manera adicional e independiente a lo dispuesto en los términos y condiciones de servicio de cada Aliado, los Usuarios deberán abstenerse de incurrir en las siguientes conductas.</p>
        <ul>
            <li>Agredir física o verbalmente a otro usuario, personal de Let’s Van y conductores de los aliados.</li>
            <li>Ingerir bebidas alcohólicas o consumir sustancias estupefacientes o enervantes, o encontrarse en estado etílico o bajo los efectos de alguna droga no médica y que no cuente con la receta o comprobante médico expedido por un profesional con cédula y firma autógrafa, debidamente facultado para emitirla.</li>
            <li>Comercializar cualquier tipo de producto dentro de la unidad.</li>
            <li>Incurrir en conductas inadecuadas, faltas a la moral, no acatar las medidas de seguridad emitidas por las autoridades, referentes a la crisis sanitaria derivada del COVID durante el ascenso y el trayecto.</li>
            <li>Dañar físicamente la unidad.</li>
            <li>Realizar cualquier actividad ilícita.</li>
            <li>No acreditar la compra de su boleto.</li>
            <li>No acreditar su identidad con las identificaciones permitidas según los presentes Términos y Condiciones.</li>
            <li>Si el Usuario incurriere en alguna de las conductas antes mencionadas se le solicitará con auxilio de la Guardia Nacional o de la Autoridad más cercana, que baje del autobús, aún si éste no ha terminado el recorrido y no ha llegado al Punto Let’s Van de destino, sin derecho alguno a cualquier tipo de compensación o reembolso, Sin menoscabo de que se le restrinja la venta futura de boletos a dicho usuario.   </li>
            <li>Quedará prohibido el ascenso a los usuarios que realicen comportamientos inadecuados, faltas a la moral o que incurran en violencia. En el caso de que estas conductas se presenten durante el trayecto del viaje, se les solicitará que detengan la conducta inadecuada y se emitirá una advertencia, y si el usuario hiciere caso omiso de la advertencia, se le podrá solicitar que baje del autobús por poner en riesgo a los demás usuarios, embajadores, y conductor, restringiendo de realizar futuras compras de boletos. </li>
            <li>Hostigar, acosar, abusar o en general, incurrir en cualesquier conductas de insinuación o de abuso sexual en perjuicio de otro Usuario, Conductor o Embajadores.</li>
            <li>Queda prohibido el ascenso a los usuarios en estado de ebriedad o bajo la influencia de drogas o enervantes.</li>
            <li>Asistir a viajes desnudos o semidesnudos.</li>
            <li>Desatender las reglas en materia de seguridad durante el viaje, incluyendo la no utilización de cinturones de seguridad.</li>
            <li>Fumar o usar cualquier tipo de cigarro electrónico o vapeador.</li>
            <li>Consumir bebidas y/o bebidas alcohólicas durante los viajes.</li>
            <li>Ceder o transferir de cualquier modo su Cuenta de Usuario a un tercero.</li>
            <li>Hacer uso ilícito, o no autorizado, o fraudulento, o contrario a lo establecido en los presentes Términos y Condiciones, de la Plataforma, los Servicios y los Medios Digitales de Let’s Van y todos los contenidos y elementos insertos en dichos Medios Digitales.</li>
            <li>Hacer ingeniería inversa o descompilar el código fuente de los Medios Digitales.</li>
            <li>Hackear los Medios Digitales o la Plataforma de Let’s Van.</li>
            <li>Hacer uso de bots generadores de tráficos para afectar el funcionamiento de los Medios Digitales o la Plataforma.</li>
            <li>Incurrir en conductas de discriminación en perjuicio de cualquier persona, por razones de género, edad, color de piel, aspecto físico, orientación sexual, estado civil o familiar, condición social, incapacidades, grupo étnico, nacionalidad, religión, condiciones de salud, opiniones políticas o cualquier otra que atente contra la dignidad humana.</li>
            <li>Ocasionar algún daño a las Unidades de nuestros Aliados o cometer algún ilícito a bordo de las referidas unidades</li>
            <li>Alterar o afectar el funcionamiento del Sitio Web o la Aplicación, independientemente de si lo realiza o no para obtener un beneficio para sí o terceros.</li>
            <li>Realizar cualquier acto contrario a la Ley o a las buenas costumbres en perjuicio de Let’s Van, los Operadores, los Transportistas Independientes, otro Usuario o cualquier tercero.</li>
            <li>Let’s Van podrá impedir temporal o permanentemente al Usuario el uso de los Servicios o el acceso a la Plataforma o Medios Digitales, así como suspender, bloquear, eliminar o cancelar la Cuenta de Usuario, unilateralmente y sin responsabilidad alguna, cuando el Usuario incurra en cualquiera de las siguientes causales.</li>
            <li>Incurrir en cualquiera de las conductas previstas en el listado que antecede.</li>
            <li>Incurrir en alguna falta a los presentes Términos y Condiciones.</li>
            <li>Realizar un contracargo o chargeback o aborde una Unidad sin pagar previamente la Tarifa.</li>
            <li>Incurrir en alguna falta a cualquier reglamento, lineamientos o regla que Let’s Van emita en relación con el Servicio, la Plataforma y los Medios Digitales.</li>
            <li>Cuando no respeten las medidas razonables de higiene, seguridad, orden o disciplina.</li>
            <li>Cuando incumplan con las reglas de operación, lineamientos de conducta, o términos y condiciones de los Transportistas Independientes.</li>
            <li>Cuando proporcione información falsa o fraudulenta a Let’s Van.</li>
        </ul>
        <p>Let’s Van podrá habilitar funcionalidades para que el Usuario califique, envíe, publique o de otro modo realice en los Medios Digitales, reseñas u opiniones. Todas las opiniones serán propiedad y responsabilidad de su autor, sin que ello implique alguna responsabilidad de cualquier naturaleza, a cargo de Let’s Van.</p>
        <p>Se encuentra prohibido enviar opiniones que de cualquier manera sean contrarias a la Ley, los presentes Términos y Condiciones o las buenas costumbres. De manera meramente enunciativa queda prohibido opiniones o cualquier contenido con contenido ofensivo, difamatorio, calumnioso, obsceno, que comprenda violencia, amenazas, constituya una apología a las últimas dos o pueda tener carácter de ilícito.</p>
        <p><strong>Artículos prohibidos.-</strong> Queda prohibido el ascenso a los usuarios en estado de ebriedad o bajo la influencia de drogas o enervantes, o bajo los efectos de sustancias tóxicas o estupefacientes o psicotrópicas o que posea algún objeto que sea considerado un riesgo para los pasajeros de los que se enumeran a continuación.</p>
        <ul>
            <li>Pinturas</li>
            <li>Solventes</li>
            <li>Tanques de gas</li>
            <li>Corrosivos</li>
            <li>Armas y explosivos</li>
            <li>Objetos punzo cortantes</li>
            <li>Inflamable</li>
            <li>Cerillos o encendedores</li>
            <li>Cualquiera que se pueda considerar un objeto peligroso a criterio del personal de Let’s Van y/o Los Aliados.</li>
            <li>Transportar armas de fuego o de cualquier tipo, objetos punzocortantes, así como cualesquier objetos peligrosos por sí mismos o por su naturaleza explosiva, tóxica o inflamable.</li>
            <li>Bebidas Alcohólicas: Éstas se transportan en la parte de abajo (cajuela) y deben estar empaquetadas y selladas.</li>
        </ul>
        <p>De ninguna manera se permitirá transportar bebidas alcohólicas en cabina y en general bebidas alcohólicas que no estén selladas y empaquetadas. </p>
    </div>
    <div class="mt-4">
        <h4 class="counter">EQUIPAJE: Documentación de equipaje</h4>
        <p>Cada usuario puede transportar hasta 35 kg de equipaje sin costo, distribuido exclusivamente de la siguiente manera.</p>
        <p><u>Equipaje de mano:</u> 1 pieza en cabina con peso máximo de 10 kg y que no exceda las dimensiones (hasta 21.5 x 15.7 x 10 pulgadas 55 x 40 x 25 cm, que quepa en la cabina en el portaequipaje de arriba/abajo del asiento).</p>
        <p><u>Equipaje documentado:</u> 1 pieza con un peso máximo de 25 kg y superficie lineal máxima de: 158cm/62".</p>
        <p>En caso de exceder el peso y/o dimensiones permitidas, el Usuario tendrá que solicitar su comprobante de pago de la tarifa vigente, que se cobrará de la siguiente manera:</p>
        <h5><strong>Tarifas de equipaje extra</strong></h5>
        <p><u>Equipaje de mano:</u> 1 pieza en cabina con peso máximo de 10 kg y que no exceda las dimensiones (hasta 21.5 x 15.7 x 10 pulgadas 55 x 40 x 25 cm, que quepa en la cabina en el portaequipaje de arriba/abajo del asiento).
            Costo: $50.00 MXN
        </p>
        <p><u>Equipaje documentado:</u> 1 pieza con un peso máximo de 25 kg y superficie lineal máxima de: 158cm/62"
            Costo: $150.00 MXN
        </p>
        <p>Se considera equipaje los objetos de uso personal, ropa, y las herramientas de un arte u oficio, los cuales deberán ser transportados en maletas, bolsas, cajas (se prohíben cajas huevo).</p>
        <p>Let’s Van, no se hace responsable por pérdida o daños de: objetos frágiles; equipos de cómputo; electrónicos; de comunicación o telefonía; electrodomésticos; dinero en efectivo o en documentos; o artículos de valor; así como los objetos que se lleven en la cabina de pasajeros; todos los anteriores viajarán bajo la responsabilidad absoluta del pasajero.</p>
        <p>Sólo se permite llevar en la cabina de pasajeros una pieza de mano por pasajero, que no exceda el tamaño de la gaveta del autobús destinada a la transportación de pertenencias pequeñas.</p>
        <p>En el Servicio Intermedio el equipaje viaja bajo la responsabilidad del pasajero, dado que no se documenta por la empresa, así como el constante ascenso y descenso de pasajeros.</p>
        <p>Se prohíbe transportar solventes, tanques de gas, pinturas, corrosivos, explosivos o armas (solo personal autorizado).</p>
        <p>Los alimentos, mariscos y artículos perecederos deben estar en empaques térmicos y sellados apropiadamente para su transportación y viajan bajo la responsabilidad del pasajero.</p>
        <p>Sólo podrán documentar y viajar equipaje que corresponda al pasajero que va a bordo del autobús.</p>
        <p>La carga y descarga de equipajes y exceso debe ser únicamente en los puntos Let’s Van, no se permite hacer paradas que no sean en los puntos Let’s Van no autorizados para subir o bajar equipaje o exceso de equipaje.</p>
        <p><strong>Pago de pérdida de equipaje.-</strong> En caso de extravío o pérdida de equipaje por el Aliado que lo transportó (permisionario), el usuario deberá reportarlo en un máximo de 72 horas, para la búsqueda minuciosa en los Puntos Let’s Van de destino y origen.</p>
        <p>Declarado como equipaje extraviado, se paga al pasajero afectado la cantidad máxima de 50 (cincuenta) UMAS por pasajero y contra entrega de la(s) contraseña(s) del equipaje documentado, sin responsabilidad alguna por el contenido del equipaje.</p>
        <p>En los casos de robo u olvido de equipaje, no es responsabilidad de la empresa.</p>
        <p>En el caso del Servicio Intermedio, el equipaje viaja bajo su responsabilidad, dado que no se documenta por la empresa.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">ACEPTACIÓN.</h4>
        <p>Los presentes Términos y Condiciones serán desplegados frente al Usuario para su aceptación expresa, la cual podrá realizarse por escrito y a través de firma autógrafa o bien por medios electrónicos mediante el llenado y/o el marcado de casillas de aceptación habilitadas en los Medios Digitales, lo anterior con fundamento en la segunda fracción del Artículo 1803 del Código Civil Federal y sus correlativos y aplicables de los Códigos Civiles de las Entidades Federativas de la República Mexicana.</p>
        <p>Los Usuarios declaran y garantizan que, previamente al uso directo o indirecto de cualquiera de los Medios Digitales, o a la instalación de los Medios Digitales en sus dispositivos, han aceptado expresamente todas y cada una de las disposiciones contenidas y previstas en los presentes Términos y Condiciones, así como la sujeción correspondiente a los mismos, en términos del párrafo que antecede.</p>
        <p>Para el supuesto de que los Usuarios por cualquier motivo no deseen obligarse en los exactos Términos y Condiciones establecidos en el presente Contrato, o de no estar conformes con la totalidad o una parte de las previsiones aquí contenidas, deberán abstenerse de hacer uso de los Servicios, realizar Reservas y/o Compras o participar en Viajes, realizar cualquier registro y utilizar o acceder a los Medios Digitales, además de abandonar inmediatamente cualquier Medio Digital que se encuentren utilizando o que hayan utilizado o donde se hayan registrado.</p>
        <p>Los Usuarios aceptan el cobro anticipado del servicio, cuando se trate de compras o reservas, hechas por éste antes de la fecha del viaje, a través de los Medios Digitales y la Plataforma, aceptando igualmente que el servicio se prestará posteriormente, es decir, en la fecha y hora que los Usuarios señalaron en su compra o reserva.</p>
        <p>La utilización de los Medios Digitales, la Plataforma o los Servicios, así como la Reserva y/o Compras de Viajes o el abordar una Unidad, presupone la aceptación expresa y plena de los presentes Términos y Condiciones.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">ACCESO Y USO.</h4>
        <p>Los Usuarios podrán registrarse en la Plataforma, accediendo a la misma a través  de los Medios Digitales, con el propósito de obtener una cuenta y una contraseña de acceso (la “Cuenta de Usuario”). Las Cuentas de Usuario son personales, intransferibles y únicamente podrán ser usadas por una sola persona, el usuario será el único responsable del uso de la misma, considerándose que sólo él tendrá acceso a la misma. </p>
        <p>El Usuario es responsable de obtener el acceso a Internet necesario para acceder a la Plataforma o a los Medios Digitales. Dicho acceso a Internet podría o no ocasionar cargos con el operador de su red móvil, cuestión que resulta en todo caso ajena a la Empresa.</p>
        <p>Asimismo, el Usuario es responsable de adquirir el hardware o los dispositivos necesarios y compatibles para acceder y utilizar a la Plataforma y a los Medios Digitales, así como mantener debidamente actualizados estos últimos.</p>
        <p>Let’s Van no garantiza que la Aplicación y los Sitios Web, funcionen correctamente en cualquier hardware o dispositivo particular.</p>
        <p>El Usuario reconoce que, debido a la funcionalidad y velocidad de la conexión a Internet y de las comunicaciones electrónicas, el Servicio podrá ser objeto de disfunciones o retrasos, sin que ello implique responsabilidad para Let’s Van.</p>
        <p>El Usuario únicamente podrá acceder a la Plataforma a través de los Medios Digitales, y únicamente para los fines establecidos en los presentes Términos y Condiciones.</p>
        <p>De manera meramente ejemplificativa, los Usuarios podrán realizar una Reserva o Compra de la siguiente forma:</p>
        <p>A través del Sitio Web, el Usuario podrá realizar la Reserva y/o Compra de un viaje. Adicionalmente, podrá realizar Reservas a través del Centro de Atención y Soporte Telefónico o WhatsApp, Redes Sociales y a través de correo electrónico. Asimismo, podrá realizar compras a bordo de la Unidad, al momento del Viaje.</p>
        <p>El Usuario ingresará a la Plataforma a través de los Medios Digitales, mediante la cual se le solicitarán los siguientes datos: Nombre completo del comprador, Nombre completo de cada uno de los viajeros, itinerario (fecha, lugar y hora del viaje), asientos, correo electrónico y número de contacto, Medio de Pago y Datos de Facturación. </p>
        <p>A continuación, la Plataforma le indicará las opciones de pago al abordar, o mediante Tarjeta de Débito o Tarjeta de Crédito. Si el Usuario selecciona proceder al pago mediante Tarjeta de Débito y/o Tarjeta de Crédito, capturará los datos correspondientes en la Plataforma, y al completar el pago, una vez realizado el cargo, recibirá de Let’s Van un correo electrónico que indicará: el nombre de los viajeros, asientos, itinerario, número de reservación por cada uno de los viajeros, identificación del Aliado con el que realizará el Viaje, y la indicación del estatus de boletos pagados.</p>
        <p>Sin en lugar de proceder al pago a través de la Plataforma, el Usuario prefiere optar por la opción de pagar a bordo, recibirá igualmente un correo electrónico de parte de Let’s Van, que indicará: el nombre de los viajeros, asientos, itinerario, número de reservación por cada uno de los viajeros, identificación del Aliado con el que realizará el Viaje, y la indicación del estatus de boletos por pagar. </p>
        <p>El Usuario también podrá hacer Reservas de Viajes a través del Centro de Atención y Soporte Telefónico o WhatsApp, Redes Sociales y a través de correo electrónico. En estos casos, le atenderá un Asesor de Atención al Cliente, quien le solicitará su número de contacto y correo electrónico, según corresponda), y le contactará a fin de asistirle, siendo el Asesor de Atención al Cliente quien realizará el proceso de Reserva a través del Sitio Web, al tiempo que atiende la llamada telefónica con el Usuario y captura los datos indicados por éste, y le acompañará hasta que el Usuario reciba el correo de confirmación de su Reserva con su número de reservación y la indicación del estatus por pagar.</p>
        <p>El número de Reservación deberá ser exhibido por el Usuario, al Embajador Let’s Van, al abordar la Unidad.</p>
        <p>El Usuario reconoce que el procedimiento descrito en líneas anteriores es meramente ejemplificativo, por lo que deberá de atenerse al procedimiento vigente indicado en los Medios Digitales, teniendo en cuenta que los presentes Términos y Condiciones podrán estar sujetos a cambios por parte de Let’s Van.</p>
        <p><strong>Uso con Cuenta de Usuario.</strong></p>
        <p>Los Usuarios podrán registrarse en la Plataforma, accediendo a la misma por medio de los Medios Digitales, con el propósito de obtener una cuenta y una contraseña de acceso (la “Cuenta de Usuario”). Las Cuentas de Usuario son personales, intransferibles y únicamente podrán ser usadas por una sola persona.</p>
        <p>Para la creación de la Cuenta de Usuario, los Usuarios deberán proporcionar la información personal correspondiente solicitada en todos los campos, con datos válidos, completos, precisos, actuales y veraces. Los Usuarios están obligados a mantener la antedicha información personal actualizada en todo momento.</p>
        <p>La Empresa se reserva el derecho de suspender cualquier Cuenta de Usuario que haya sido registrada con información que se estime como falsa, inexacta o engañosa. Let’s Van se reserva el derecho de solicitar, en cualquier momento, información o documentación a los Usuarios con el propósito de verificar la veracidad de la información proporcionada, así como de suspender temporal o definitivamente a aquellos Usuarios cuya información no haya podido ser corroborada, sin que otorgue derecho al Usuario a resarcimiento alguno.</p>
        <p>Los Usuarios deberán crear su Cuenta de Usuario a través de los Medios Digitales y de conformidad con el procedimiento que para tal efecto se establezca en los Medios Digitales. Let’s Van podrá cambiar dicho procedimiento sin necesidad de otorgar previo aviso a los Usuarios o de modificar el presente instrumento.</p>
        <p>Todos los Usuarios declaran que cuentan con capacidad para contratar, de acuerdo con la legislación aplicable en sus respectivos domicilios. Únicamente podrán solicitar la habilitación de una Cuenta de Usuario las personas que tengan mayoría de edad, es decir, dieciocho (18) años cumplidos al momento de registrarse en la Plataforma. En caso de que una persona menor de edad se registre en la Plataforma, las personas que tengan patria potestad, la tutela o la supervisión del menor serán solidariamente responsables por cualesquier eventos o situaciones que puedan ser ocasionadas por el menor, incluyendo el pago de las Tarifas y de los Cargos Adicionales que pudiera generar el uso de su Cuenta de Usuario, así como todos los daños y perjuicios que ocasione el menor.</p>
        <p>Al momento de crear una Cuenta de Usuario, al Usuario se le solicitará señale una contraseña, misma que será requerida cada que el Usuario inicie sesión en la Plataforma. El Usuario será responsable del resguardo, custodia, memorización y conservación de su contraseña; por consecuencia, el Usuario asumirá todos los riesgos y será responsable de todos los daños y perjuicios que pudieran derivarse de su uso indebido, así como de la revelación, olvido o extravío de la misma.</p>
        <p>En caso de olvido de la contraseña o de cualquier otra circunstancia que suponga un riesgo de acceso y/o utilización por parte de terceros no autorizados, el Usuario lo comunicará inmediatamente al Centro de Atención y Soporte de la Empresa.</p>
        <p>Es responsabilidad del Usuario memorizar su contraseña. Let’s Van podrá o no contar con métodos de recuperación de contraseñas, y no estará obligado a asistir al Usuario para la recuperación de la misma.</p>
        <p>Todas las operaciones realizadas a través de una cuenta de usuario se presumirán efectuadas por el titular de la Cuenta. Asimismo, el titular de la cuenta será responsable y pagará los gastos, daños y/o perjuicios que se deriven de cualquier acceso o uso no autorizado a su Cuenta.</p>
        <p>Los Usuarios reconocen y aceptan que el acceso y uso de la Plataforma y los Medios Digitales, así como la correspondiente participación en los Viajes, es bajo su única y exclusiva responsabilidad.</p>
        <p><strong>Uso sin Cuenta de Usuario.</strong></p>
        <p>Todas aquellas personas que accedan a, o utilicen los Medios Digitales y la Plataforma, o que participen en los Viajes, o realicen Reservas y/o Compras, aun sin contar con una Cuenta de Usuario, reconocen que dichos actos implican la aceptación expresa y plena de los presentes Términos y Condiciones</p>
        <p>Cuando los Usuarios no cuenten con una Cuenta de Usuario podrán realizar Reservas a través de los Medios Digitales sin una Cuenta de Usuario, para lo cual deberán seguir el proceso que les indique la Plataforma, y llenar todos los formularios e indicar todos los datos que les requiera la Plataforma.</p>
        <p>El proceso y requisitos para realizar Reservas y/o Compras puede ser modificado sin previo aviso por Let’s Van y no implicará una modificación a los presentes Términos y Condiciones.</p>
        <p>Los Usuarios deberán proporcionar la información personal correspondiente en todos los campos, con datos válidos, precisos, completos, actuales y veraces. Los Usuarios están obligados a mantener la antedicha información personal actualizada en todo momento.</p>
        <p>En caso de que una persona menor de edad solicite o haga uso de los Servicios de Let’s Van, o bien, use la Plataforma o los Medios Digitales, las personas que tengan la patria potestad, la tutela o la supervisión del menor serán solidariamente responsables por cualesquier eventos o situaciones que puedan ser ocasionadas por el menor, incluyendo el pago de cualquier tipo de contraprestación o cargos adicionales que se pudieran generar por los Servicios, así como cualquier daño y/o perjuicio ocasionado por el menor.</p>
    </div>
    <div class="my-4">
        <h4 class="counter">PLATAFORMA.</h4>
        <p>La “Plataforma” es una herramienta digital de intermediación entre los Usuarios y los Aliados, por medio del cual los Usuarios realizan Reservas y/o Compras de Viajes. Se podrá acceder a la Plataforma a través de los Medios Digitales.</p>
        <p>La Empresa hace del conocimiento de los Usuarios que presta única y exclusivamente los siguientes servicios:</p>
        <p>1. Gestión de Reservas y/o Compras e intermediación con Aliados quienes son Transportistas Independientes, es decir, otorga a los Usuarios la oportunidad de realizar una Reserva y/o Compra de boleto para un asiento en las Unidades respecto de los Viajes que realizan los Aliados quienes son Transportistas Independientes.</p>
        <p>2. Administración de un Centro de Atención y Soporte, con el propósito de atender las solicitudes de orientación, asesoría y apoyo de los Usuarios relacionadas con el uso de los Medios Digitales y con el Servicio.</p>
        <p>La Empresa pone la Plataforma a disposición de los Usuarios conforme se expresa a lo largo del presente documento. Por lo tanto, el acceso a la Plataforma no constituye por sí misma un servicio, sino que es otorgado por motivo de la Licencia de Uso que se estipula más adelante, en secciones posteriores del presente instrumento.</p>
        <p>Al aceptar o suscribir los presentes Términos y Condiciones, los Usuarios quedan informados y aceptan que Let’s Van no presta servicios de transporte, ratificando de conformidad para todos los efectos legales a que haya lugar.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">CONTRAPRESTACIÓN.</h4>
        <p>El Usuario tendrá que pagar una contraprestación por concepto de los Servicios, así como una contraprestación por concepto de los Viajes proporcionados por los Aliados  (en adelante, las “Tarifas”).</p>
        <p>Dichas Tarifas serán cubiertas directamente a través de los Medios Digitales al momento de realizar una Reserva de un Viaje, o bien, presencialmente momentos antes de abordar una Unidad.</p>
        <p>Las Tarifas se determinarán por cada Trayecto, serán calculadas mediante herramientas automatizadas en la Plataforma tomando en consideración el Trayecto elegido por el Usuario, cuyo importe total será desplegado de forma previa a la selección de un Trayecto o a la realización de una Reserva y/o Compra.</p>
        <p>En cualquier caso, el Usuario no podrá abordar una Unidad de un "Aliado sin cubrir antes las Tarifas.</p>
        <p>El Usuario deberá de pagar junto con las Tarifas los impuestos aplicables.</p>
        <p>Las Tarifas pagadas no serán reembolsables.</p>
        <p>Las Tarifas se publicarán en los Medios Digitales de Let’s Van, y están sujetas a cambio o modificación.</p>
        <p>A las Tarifas únicamente podrán aplicarse los Descuentos Permitidos. Los Descuentos Permitidos estarán sujetos a los términos específicos que se publiquen en los Medios Digitales. La Empresa se reserva el derecho de restringir el uso de los Descuentos Permitidos a los Usuarios que hagan un uso inadecuado, ilícito o abusivo de aquéllos, a juicio de Let’s Van. Lo previsto más adelante a propósito de Operaciones Fraudulentas será aplicable a las promociones, descuentos, invitaciones y códigos promocionales que ofrezca la Empresa.</p>
        <p>Por motivos de seguridad, Let’s Van podrá vetar, bloquear, cancelar o anular cualquier Medio de pago. Let’s Van se reserva el derecho a modificar, ampliar, reducir, establecer y/o eliminar cualquier Medio de Pago en cualquier momento, según lo estime conveniente.</p>
        <p>La suscripción o aceptación de los presentes Términos y Condiciones implica la correspondiente aceptación incondicional de las Tarifas, para todos los efectos legales a que haya lugar.</p>
        <p>Todo lo relativo a las cancelaciones y las Penalizaciones se encuentra previsto en secciones posteriores del presente instrumento. No será requisito para la aplicación de las Penalizaciones que las mismas se encuentren publicadas en los Medios Digitales, por tratarse de cobros originados por la generación de daños a la Unidad o a terceros y que corresponden a la responsabilidad civil imputable al Usuario infractor.</p>
        <p>Los Usuarios autorizan expresamente que Let’s Van aplique y cargue las Penalizaciones en el Medio de Pago.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">BIS.- AGREGADOR BANCARIO.</h4>
        <p>Los Usuarios autorizan expresa e irrevocablemente a Let’s Van la contratación con uno o más Agregadores Bancarios, con el propósito de que sean dichas empresas especializadas las que realicen directamente los cobros de las Tarifas que paguen los Usuarios por conducto de los Medios de Pago. Los Agregadores Bancarios captarán y procesarán, de forma privada y restringida, los datos personales financieros o bancarios de los Usuarios que sean exclusivamente necesarios para realizar el cobro de las Tarifas por conducto de tarjeta bancaria o medios electrónicos de pago.</p>
        <p>Actualmente, Let’s Van no recibe, almacena, ni mantiene ninguna clase de datos financieros, toda vez que Let’s Van utiliza los servicios de índole Gateway y/o aceptación de pagos electrónicos brindados por compañías especializadas. Se hace del conocimiento de los Usuarios que, a la fecha, se encuentran conectados a la Plataforma los siguientes Agregadores Bancarios:</p>
        <p class="mb-0">MERCADOPAGO</p>
        <a href="https://mercadopago.com/">https://mercadopago.com/</a>
        <p class="mt-3">Let’s Van podrá contratar los servicios de Agregadores Bancarios distintos de los antes enunciados, sin que ello se considere una modificación a los presentes Términos y Condiciones.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">POLÍTICAS DE RESERVACIÓN Y COMPRA.</h4>
        <p>El Usuario podrá realizar reservaciones de viaje a través de la Plataforma, del Centro de Atención y Soporte Telefónico o WhatsApp, correo electrónico, y mediante mensajes directos a través de las redes sociales de Let’s Van.</p>
        <p>Las compras de viajes podrán ser realizadas por los Usuarios mediante la Plataforma en el Sitio Web, y por vía telefónica a través del Centro de Atención y Soporte Telefónico, o al abordar la Unidad.</p>
        <p>Las reservaciones y compras de viajes se llevarán a cabo con observancia de las tarifas publicadas en el Sitio Web, las cuales aplicarán exclusivamente, es decir, no sufrirán variación alguna, en los casos en que el Usuario complete las referidas operaciones de reserva o compra, es decir, cuando reciba un correo electrónico de parte de Let’s Van, con el número de reservación, y los demás datos correspondientes conforme a los presentes Términos y Condiciones, con indicación del estatus pagado o por pagar, según corresponda, tales como: el nombre de los viajeros, asientos, itinerario, número de reservación por cada uno de los viajeros, identificación del Aliado con el que realizará el Viaje, y la indicación del estatus de boletos pagado o por pagar.</p>
        <p>El Usuario conoce y acepta que, salvo en el caso de que se complete la reservación o compra de un viaje, las tarifas publicadas en el Sitio Web podrán sufrir modificaciones atendiendo a los límites legales correspondientes a la regulación tarifaria.</p>
        <p>En los casos de reservaciones hechas mediante el Centro de Atención y Soporte Telefónico o WhatsApp, a través de los números indicados en los presentes Términos y Condiciones, y mediante correo electrónico, o a través de redes sociales, se considerarán completadas, cuando el Usuario reciba un correo electrónico de parte de Let’s Van con el número de reservación, y los demás datos correspondientes, conforme a los presentes Términos y Condiciones, con indicación del estatus por pagar. Por su parte, se considera que una compra ha sido completada, a través del Centro de Atención y Soporte Telefónico o WhatsApp, o a través de correo electrónico, cuando se le ha suministrado al Usuario un número de reservación, y se le ha aplicado el correspondiente cargo a través del medio de pago que éste suministró.</p>
        <p>En el caso de las reservas que el Usuario pretenda pagar al momento en el que se produzca el viaje, la tarifa establecida se mantendrá únicamente hasta que el Usuario realice el correspondiente pago al abordar la Unidad, mediante pago electrónico con el uso de clip, o pago en efectivo, según lo prefiera. </p>
        <p>Al acceder al servicio de Compra de viajes a través de los números del Centro de Atención y Soporte Telefónico; o Reservas realizadas mediante Centro de Atención y Soporte Telefónico o WhatsApp, correo electrónico, o mensajes directos en las redes sociales de Let’s Van, el Usuario consiente de manera expresa a Let’s Van para que realice el tratamiento de sus datos personales, incluidos sus datos financieros, conforme a lo establecido en el Aviso de Privacidad de Let’s Van que se encuentra en el Sitio Web.</p>
        <p>El acceso por parte del Usuario a los servicios mediante la Plataforma en el Sitio Web, o a través de los números de Centro de Atención y Soporte Telefónico o WhatsApp, y a través de correo electrónico, o mensajes directos en las redes sociales de Let’s Van, suministrando para ello su información personal y financiera, implica su aceptación de los presentes Términos y Condiciones, así como su manifestación expresa de consentimiento para que Let’s Van proceda al tratamiento de sus datos personales de conformidad con lo dispuesto en el Aviso de Privacidad que se encuentra en el Sitio Web.</p>
        <p>En los casos de reservaciones cuyo pago aún no se hubiera procesado, la misma estará sujeta a disponibilidad que hubiera al momento en que se realice el pago y se finalice el proceso de compra.</p>
        <h5>POLÍTICAS DE PAGO EN COMPRAS Y RESERVAS TELEFÓNICAS</h5>
        <p>En las compras realizadas a través del Centro de Atención y Soporte Telefónico, los Usuarios suministrarán la siguiente información relativas a sus datos personales, al ser atendido, el Usuario será informado de los términos del Aviso de Privacidad Let’s Van, y se le informará que el mismo se encuentra a su disposición en la dirección URL https://letsvan.com.mx/privacidad.</p>
        <p>Asimismo, a fin de realizar la compra, se lo solicitará al Usuario a siguiente información:</p>
        <ul>
            <li>Nombre completo de los pasajeros.</li>
            <li>Fecha de nacimiento.</li>
            <li>Número de boletos requeridos, determinando si se trata de adultos, niños, casos Inapam, personas con capacidades especiales, y demás información relacionada.</li>
            <li>Identificación Oficial con foto (INE, Pasaporte).</li>
            <li>Correo electrónico.</li>
            <li>Itinerario de viaje: Fecha y lugar de origen y destino.</li>
            <li>Tipo de viaje (sencillo o redondo).</li>
            <li>Datos de su tarjeta de débito o crédito con la cual realizará la compra, indicando el número de su tarjeta, código de seguridad y fecha de vencimiento, con lo cual, autoriza el cargo a su medio de pago, por concepto del pago de la tarifa correspondiente.</li>
        </ul>
        <p>Let’s Van dará el tratamiento de los datos personales suministrados por el Usuario, conforme a lo establecido en su Aviso de Privacidad que se encuentra en la dirección electrónica URL <a href="https://letsvanan.com.mx/privacidad">https://letsvanan.com.mx/privacidad</a></p>
        <p>Antes de procesar la compra, Let’s Van confirmará a través de su sistema la correcta captura de la información solicitada al Usuario, a fin de evitar errores en la operación.</p>
        <p>Una vez hecho el cargo en el medio de pago suministrado por el Usuario, y confirmada la transacción exitosa, se le proporcionará al Usuario el número de reservación, y se le enviará toda la información correspondiente a la compra a su correo electrónico suministrado.</p>
        <p>Let’s Van se reserva el derecho de excluir modalidades de pago, cuando resulte conveniente a sus intereses, y por razones operativas.</p>
        <p>Cuando el Usuario realice Reservas a través del Centro de Atención y Soporte Telefónico o WhatsApp, mediante correo electrónico, y/o a través de mensaje directo en redes sociales, podrán ser pagadas a bordo de la Unidad, previo a la salida del viaje, en efectivo o mediante tarjeta de débito o crédito. Cuando se cuente con una Reserva previa, el pago del boleto en la Unidad al momento del viaje estará sujeto a la disponibilidad de cupo.</p>
        <p>Let’s Van implementará las medidas de seguridad que sean necesarias para evitar transacciones fraudulentas, reservándose Let’s Van el derecho de bloquear a los Usuarios de la plataforma que incurran en transacciones que se consideren fraudulentas, todo ello en protección de la seguridad del Usuario. En tal sentido, Let’s Van podrá enviar correos electrónicos de manera aleatoria a los Usuarios, mediante el cual le solicitará información como su identificación, imagen de su tarjeta eliminando datos sensibles, que debe ser respondido en el tiempo determinado por Let’s Van, con la finalidad de realizar una validación de la transacción realizada por el usuario. En caso de no recibir la información solicitada, Let’s Van podrá realizar la cancelación de la Reserva o la Compra.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">LICENCIA DE USO.</h4>
        <p>Sujeto a lo previsto en los presentes Términos y Condiciones, Let’s Van otorga a los Usuarios y los Usuarios aceptan de Let’s Van, una licencia limitada, personal, no cedible, no sublicenciable, intransferible, revocable y no exclusiva, para el uso sin fines lucrativos de la Plataforma y el resto de los Medios Digitales dentro del territorio de México (la “Licencia de Uso”). Ningún código fuente o licencia para usar código fuente son otorgados bajo los términos de la presente sección.</p>
        <p>Los Usuarios se comprometen a hacer un uso adecuado y lícito de los Medios Digitales, de conformidad con la Normatividad Aplicable, el presente instrumento, la moral, las buenas costumbres generalmente aceptadas y el orden público. Los Usuarios deberán abstenerse de incurrir en las siguientes conductas: (i) hacer un uso inadecuado, ilícito o fraudulento de los Medios Digitales; (ii) acceder o intentar acceder a recursos restringidos o no autorizados dentro de los Medios Digitales; (iii) utilizar los Medios Digitales con fines o propósitos ilícitos, ilegales, contrarios a lo establecido en el presente instrumento, lesivos de los derechos o intereses de terceros, o que de cualquier forma puedan dañar, inutilizar o sobrecargar o impedir la normal utilización o disfrute del Servicio; (iv) provocar daños en los Medios Digitales o en los sistemas de sus proveedores o de terceros; (v) introducir, difundir o realizar actos tentativos o tendentes a distribuir virus informáticos o cualesquier otros sistemas físicos o lógicos que sean susceptibles de causar daños en los sistemas de Let’s Van, de sus proveedores o de terceros; (vi) intentar, acceder, utilizar y/o manipular los datos de Let’s Van; terceros proveedores y otros Usuarios; (vii) utilizar algún sistema automático, incluyendo “robots”, “spiders” o “scrapers” que envíen más peticiones a los servidores de Let’s Van que los que un usuario humano podría razonablemente utilizar en el mismo periodo de tiempo (viii) reproducir o copiar o distribuir cualesquier elementos insertos en los Medios Digitales, sin contar con la autorización correspondiente; y (ix) realizar o intentar realizar ingeniería inversa, descompilar o hacer compilación inversa, desensamblar, listar, imprimir o mostrar el software, firmware, middleware o cualquier otra parte del código fuente o compilado que integra la Plataforma y cualquiera de sus programas o componentes, o por cualquier otro medio obtener el código fuente u otra información patrimonial de los Medios Digitales.</p>
        <p>Asimismo, queda estrictamente prohibida la realización de “Operaciones Fraudulentas” en la Plataforma. Para efectos del presente documento, se entenderá por Operaciones Fraudulentas, cualquier acto realizado por los Usuarios para obtener un lucro o beneficio indebido, incluyendo sin limitar la suplantación de identidades; la creación de cuentas falsas o cuentas dobles de usuario; el abuso de los Descuentos Permitidos; la petición o la solicitud de Viajes “fantasma”, inusuales o inexistentes; el ingreso de información financiera o bancaria falsa, o previamente sustraída a terceros; la confabulación con cualquier otro Usuario o con cualquier personal de Let’s Van o con cualquier Operador o "EL ALIADO"  para realizar conductas fraudulentas; y en general, cualquier acto ilícito, o cualquier acto aislado o reiterado que tenga como propósito engañar a la Plataforma o a la Empresa para obtener un beneficio o lucro indebido.</p>
        <p>Los Usuarios reconocen que Let’s Van no garantiza el acceso y uso continuado o ininterrumpido de los Medios Digitales. Los Usuarios reconocen que los Medios Digitales podrán no estar disponibles debido a dificultades técnicas, fallas en el internet, afectaciones en las redes de telecomunicaciones, o por cualquier circunstancia ajena a la Empresa.</p>
        <p>Los Usuarios renuncian expresa e irrevocablemente a imputar responsabilidad alguna a Let’s Van o exigir resarcimiento patrimonial alguno, en virtud de perjuicios resultantes de las mencionadas dificultades, así como por cualquier otra clase de daños, incluyendo daños directos, daños indirectos, daños incidentales, daños especiales, daños ejemplares o punitivos, daños emergentes, lucro cesante, pérdida de datos, lesiones personales, daño a la propiedad y/o daños consecuenciales que surjan o experimenten por el mal funcionamiento o la interrupción del funcionamiento de la Plataforma o de los Medios Digitales.</p>
        <p>La Empresa podrá realizar modificaciones, alteraciones, adaptaciones o ajustes a los Medios Digitales, su interfaz gráfica o sus funcionalidades, sin que ello se considere una modificación de los presentes Términos y Condiciones.</p>
        <p>Let’s Van se reserva el derecho de revocar la Licencia de Uso, en caso de determinar una infracción a lo dispuesto en la presente sección, sin necesidad de previa interpelación judicial o extrajudicial o de obtener una declaración judicial o administrativa para tal efecto. La revocación será notificada al Usuario infractor por cualquier medio e implicará la pérdida de acceso definitiva a la Plataforma.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">FACTURACIÓN</h4>
        <p>El Usuario podrá facturar los pagos que se hubieran realizado por concepto de Tarifas, Beneficios Adicionales y/o Cambios y/o Cancelaciones en la Compra y/o penalizaciones previstas dentro de estos términos y condiciones, dentro del mes en el que se hizo la compra y hasta 7 (siete) días después del mes en el que haya realizó la compra. </p>
        <p>Para solicitar su factura el usuario deberá enviar un correo electrónico a la dirección contacto@letsvan.com.mx</p>
        <p>Los usuarios tienen 30 días naturales para generar la factura electrónica a partir de la fecha de  compra, una vez pasado este tiempo no se podrá facturar.</p>
        <p>La fecha que debe tomar en cuenta para la generación de su solicitud es la fecha de pago.</p>
        <p>El proceso de facturación aplicará de la siguiente manera:</p>
        <p>Cuando se realice una compra a través de los medios electrónicos y/o digitales, la factura se podrá solicitar al momento de acreditación del pago.</p>
        <p>Cuando se realiza el pago a través de los medios electrónicos y/o digitales, se puede solicitar la factura de manera inmediata a través del correo electrónico contacto@letsvan.com.mx</p>
        <p>El portal es para la facturación de compras por boletos con los aliados, se excluyen las compras de alimentos y servicios abordo.</p>
        <p>Para procesar la solicitud se requiere contar con su clave de Reserva, nombre(s) y apellido(s) tal cual aparece en su confirmación de Compra. Para reservaciones con más de un usuario se puede utilizar cualquier nombre y apellido del itinerario.</p>
        <p>Deberá capturar toda su información fiscal requerida como RFC, SIN UTILIZAR ACENTOS, CARACTERES ESPECIALES COMO ¨ *, °, |, / o etc.</p>
        <p>En caso de que tenga dudas relacionadas a la emisión del CFDI favor de enviar sus comentarios (incluyendo los datos de su Compra y folio de factura) a través del correo electrónico contacto@letsvan.com.mx</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">IMPUESTOS, CUOTAS Y CARGOS.</h4>
        <p>Los impuestos, cuotas y cargos que impongan los gobiernos federales, estatales y/o municipales, así como las autoridades o con relación al o los servicios contratados, deberán ser pagados por el usuario junto con las Tarifas aplicables.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">POLÍTICA DE OBJETOS OLVIDADOS.</h4>
        <p>Los Usuarios acuerdan sujetarse plenamente y sin reservas a la Política de Objetos Olvidados prevista en la presente sección. En caso de que cualquier Usuario no acepte o no esté de acuerdo con la Política de Objetos Olvidados aquí establecida, deberá de abstenerse de utilizar los Medios Digitales, los Servicios y la Plataforma así como de participar en, o reservar y/o Comprar Viajes, o abordar una Unidad.</p>
        <p>Let’s Van no se hará responsable en ningún momento por objetos olvidados en los autobuses de los aliados, los Usuarios aceptan que el cuidado de sus pertenencias es su responsabilidad.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">POLÍTICA DE CANCELACIONES Y PENALIZACIONES.</h4>
        <p>Los Usuarios acuerdan sujetarse plenamente y sin reservas a las Políticas de Cancelación y Penalizaciones previstas en la presente sección. En caso de que cualquier Usuario no acepte o no esté de acuerdo con la Política de Cancelaciones y Penalizaciones aquí establecida, deberá de abstenerse de utilizar los Medios Digitales, los Servicios, y la Plataforma así como de participar en, o reservar y/o Comprar Viajes, o abordar una Unidad.</p>
        <p><strong>Devoluciones por causas imputables a Let’s Van o los Aliados.-</strong></p>
        <p>La devoluciones aplicarán únicamente cuando se produzca una cancelación por parte de los aliados o Let’s Van, derivado de cambios operativos que tengan lugar conforme a lo establecido en los presentes Términos y Condiciones, Let’s Van realizará el reintegro de lo erogado por el Usuario, de la siguiente manera:</p>
        <p>Let’s Van verificará si fue materializado el cobro a través del Agregador Bancario. Si se realizó el cobro, Let’s Van, a través de la plataforma del Agregador de Pagos, gestionará la devolución de lo pagado a través del mismo medio de pago electrónico (Tarjeta de Débito o Tarjeta de Crédito), en la misma institución bancaria desde la cual el Usuario realizó el pago.</p>
        <p>Para concluir el proceso de devolución a través del Agregador Bancario, éste generará un código ID que Let’s Van le suministrará al Usuario a través de su correo electrónico que suministró al hacer su registro en la Plataforma Let’s Van, con el objeto de que pueda hacer el seguimiento ante su institución bancaria, hasta el momento en que la devolución se encuentre reflejada en su medio de pago.</p>
        <p>El proceso de devolución puede oscilar entre 3 y 60 días, conforme a los tiempos del proceso del Agregador Bancario.</p>
        <p>Si la compra se hubiera hecho en efectivo a través de los Puntos de venta físicos y/o en los puntos Let’s Van o abordo, el usuario deberá solicitar la devolución al correo electrónico contacto@letsvan.com.mx, donde deberá adjuntar, el nombre completo del usuario, número de cuenta bancaría a nombre de quien realizó la compra, banco, y un breve resumen del porqué  solicita la devolución. Éste  proceso de devolución puede oscilar entre 10 y  20 días hábiles.</p>
        <p>El Aliado será el único responsable frente a los Usuarios por la prestación de los servicios independientes de transporte, como lo puede ser, de manera meramente enunciativa, en el caso de retrasos, cancelaciones, accidentes y otros percances relacionados con los servicios de los Aliados quienes son prestadores de servicio de autotransporte federal de pasajeros independientes. </p>
        <p>En este acto, los Usuarios renuncian a reclamar a Let’s Van cualquier concepto por dichos servicios de transporte independiente.</p>
        <p>El Usuario otorga su consentimiento para que Let’s Van efectúe los cargos adicionales que sean necesarios, cuando el Usuario cause algún daño y/o perjuicio a Let’s Van o a algún Aliado  (en adelante, las “Penalizaciones”); de manera meramente enunciativa, cuando el Usuario ensucie, manche, vierta o derrame algún líquido y/o sustancia en los vehículos o unidades de los Transportistas Independientes o dañe de cualquier manera dichos vehículos o unidades, como se marca en el apartado de limpieza especial.</p>
        <p>Dichos cargos se harán al medio de pago utilizado por el Usuario para pagar las Tarifas, o cualquier otro método de pago que el Usuario haya proporcionado a Let’s Van o registrado en el Sitio Web o Aplicación.</p>
        <p>Ciertas Penalizaciones (aplicables a eventos dañosos específicos) se encontrarán publicadas en los Medios Digitales. Sin embargo, atendiendo a la gravedad del asunto, las penalizaciones podrán ser determinadas caso por caso, con base en el reporte y/o en el dictamen que realice el Aliado afectado y demás circunstancias necesarias para determinar y cuantificar el daño ocasionado a las Unidades o a cualquier persona.</p>
        <p><strong>Cancelaciones.-</strong> A los usuarios que hayan realizado una compra a través de los medios digitales o físicos y que deseen realizar cualquier cambio  lo deberán realizar con un mínimo de 8 (ocho) horas de anticipación al horario de salida marcado en su correo de confirmación, de no hacerlo con las 8 horas de antelación, no se podrá realizar ningún cambio o modificación en la reserva y/o compra, el usuario no tendrá derecho  al cambio de su boleto,</p>
        <p>El usuario que desee realizar cambios o modificaciones en la compra por causas ajenas a Let’s Van o a sus aliados, es decir que desee modificar o cancelar el boleto por motivos imputables al usuario, se le cobrará un 10 % (diez por ciento) del valor del boleto para poder realizar el cambio, ya sea por fecha u horario, el cual estará sujeto a la disponibilidad que haya en el momento del cambio. </p>
        <p>Si el usuario decide cancelación el boleto comprado, por causas imputables al usuario, es decir por decisión del mismo, ni Let’s Van ni el Aliado estará obligado a realizar ninguna devolución. Asimismo, será causa de penalización para el Usuario que haya realizado una Reserva a través de los medios digitales y no acuda al Viaje, la cual podrá ser desde restringir nuevas reservas y/o compras hasta una pena por el monto del 50 % del boleto más el costo del mismo.</p>
        <p><strong>Reservaciones.-</strong> Si el usuario opta por la opción de reservar a través de los medios electrónicos disponibles de Let’s Van y pagar al momento del abordaje, su reserva estará sujeta a disponibilidad según la ocupación de los boletos pagados con antelación. </p>
        <p>Horarios: Si el usuario no cumple con los tiempos establecidos en el apartado  IV.- OBLIGACIONES DE LOS USUARIOS, respecto a traslados (15 minutos de anticipación en los puntos Let’s Van de salida, para revisión de documentos: número de reservación de compra digital e identificación oficial  vigente); y, en caso de documentar equipaje (25 minutos de anticipación a la hora de salida marcada en su boleto), no tendrá derecho a la devolución del monto pagado por el boleto, a ninguna compensación monetaria, descuento, cupón, cambio de horario, cambio de fecha o ningún otro. </p>
        <p>Cambio operativos y/o de fuerza mayor. Let’s Van y/o los Aliados podrá hacer  cambios en:</p>
        <ul>
            <li>Horarios de salida y llegada. </li>
            <li>Ubicación de los Puntos Let’s Van de destino y origen.</li>
            <li>Recorrer horarios.</li>
            <li>Y cualquier otro que sea necesario, según las necesidades de Let’s Van y/o los aliados   respecto de las necesidades operativas y/o de fuerza mayor que se presenten.</li>
        </ul>
    </div>
    <div class="mt-4">
        <h4 class="counter">CENTRO DE ATENCIÓN Y SOPORTE.</h4>
        <p>Para realizar cualquier solicitud, queja o reporte relacionado con los Servicios de la Plataforma o con los Medios Digitales, el  Usuario deberá comunicarse al Centro de Atención y Soporte de Let’s Van dentro del plazo máximo de cinco (5) días naturales posteriores al acontecimiento que deseen reportar o cuya aclaración solicita (las “Aclaraciones”). </p>
        <div>
            <p>Centro de Atención y Soporte:</p>
            <ul>
                <li>Teléfono: 4434489901</li>
                <li>Whatsapp: 4434489901</li>
                <li>Correo electrónico: contacto@letsvan.com.mx</li>
            </ul>
            <p>Los horarios de atención vigentes son:</p>
            <ul>
                <li>Atencion via telefonica de 08:00 am at 10:00 pm.</li>
                <li>Atencion via Whatssapp y Correo electrónico de 08:00 am a 10:00 pm.</li>
            </ul>
        </div>
    </div>
    <div class="mt-4">
        <h4 class="counter">PRIVACIDAD.</h4>
        <p><strong>Le informamos que los datos personales que usted ha proporcionado son confidenciales y serán tratados de conformidad con lo establecido en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares. Para mayor información acerca del tratamiento de sus datos personales y de los derechos que puede hacer valer, usted puede consultar nuestro aviso de privacidad en la dirección https://letsvan.com.mx/privacidad.</strong></p>
        <p>Al suscribir o aceptar los presentes Términos y Condiciones, los Usuarios declaran que han leído el Aviso de Privacidad de Let’s Van, que se encuentra a su disposición en el Sitio Web. </p>
        <p>Para más información sobre el tratamiento de sus datos personales, los Usuarios deberán consultar el Aviso de Privacidad.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">APLICABILIDAD.</h4>
        <p>De conformidad con lo establecido en secciones precedentes del presente instrumento, los Términos y Condiciones son aplicables a los Usuarios que se ubiquen en el territorio de México.</p>
        <p>Los Usuarios que residan en otra jurisdicción y pese a ello decidan solicitar y/o hacer uso de los Servicios objeto de los presentes Términos y Condiciones lo harán bajo su propia responsabilidad y riesgo, debiéndose asegurar dichos Usuarios que tal uso cumple con la legislación local aplicable en la jurisdicción donde el Usuario solicite o haga uso de los Servicios o acceda a la Plataforma o a los Medios Digitales.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">DERECHOS DE PROPIEDAD INTELECTUAL E INDUSTRIAL.</h4>
        <p>Todo el contenido incluido o disponible en los Medios Digitales, incluyendo el texto, gráficos, diseño web, interfaz, código, modelos y/o software de la Plataforma está protegido por la legislación aplicable en México y en el extranjero, en su caso, en materia de propiedad intelectual y protección de derechos de autor.</p>
        <p>Los Usuarios reconocen y aceptan que todos los derechos de propiedad intelectual e industrial sobre los Medios Digitales y sobre todos los contenidos y elementos insertos en los Medios Digitales (incluyendo sin limitar marcas, logotipos, figuras, nombres comerciales, textos, imágenes, gráficos, diseños, sonidos, bases de datos, software, modelos, diagramas de flujo, presentaciones, y elementos de audio y de video) pertenecen a Let’s Van (la “Propiedad Intelectual”).</p>´
        <p>Se encuentra estrictamente prohibida cualquier reproducción, distribución, transmisión, copia, alteración, explotación, publicación, difusión o disposición de la Propiedad Intelectual, sin el consentimiento previo y por escrito de un representante legal de Let’s Van.</p>
        <p>Cualquier uso o explotación de la Propiedad Intelectual, que no sea autorizado por un representante legal de Let’s Van previamente y por escrito, será motivo suficiente para cancelar la Cuenta del Usuario o para suspender temporal o permanentemente a un Usuario, sin perjuicio de las sanciones administrativas, civiles y penales a las que sea acreedor el infractor.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">EXCLUSIÓN DE GARANTÍAS Y RESPONSABILIDAD.</h4>
        <p>El Usuario reconoce y acepta que el acceso a la Plataforma y los Medios Digitales y su uso es bajo su exclusiva responsabilidad. En ningún caso Let’s Van será responsable del uso que el Usuario y/o terceros pudieran hacer de la Plataforma y/o los Medios Digitales, ni de los daños y perjuicios que pudieran derivarse de ello.</p>
        <p>Let’s Van no garantiza la disponibilidad y continuidad del funcionamiento de los Medios Digitales. En consecuencia, Let’s Van no será en ningún caso responsable por cualesquier daños y perjuicios que puedan derivarse de: (i) la falta de disponibilidad o accesibilidad a los Medios Digitales; (ii) la interrupción en el funcionamiento de los Medios Digitales por fallos informáticos, averías telefónicas, desconexiones, retrasos o bloqueos causados por deficiencias o sobrecargas en las líneas telefónicas, centros de datos, en el sistema de internet o en otros sistemas electrónicos, producidos en el curso de su funcionamiento; y (iii) otros daños que puedan ser causados por terceros mediante intromisiones no autorizadas ajenas al control de Let’s Van.</p>
        <p>Let’s Van no garantiza la ausencia de malware ni de otros elementos en los Medios Digitales introducidos por terceros ajenos a Let’s Van que puedan producir alteraciones en los sistemas físicos o lógicos del Usuario o en los documentos electrónicos y ficheros almacenados en sus sistemas. En consecuencia, la Empresa no será en ningún caso responsable de cualesquier daños y/o perjuicios de toda naturaleza que pudieran derivarse de la presencia de malware u otros elementos que puedan producir alteraciones en los ordenadores o dispositivos de los Usuarios.</p>
        <p>Let’s Van no garantiza que terceros no autorizados puedan conocer las condiciones, características y circunstancias en las cuales los Usuarios acceden a la Plataforma. En consecuencia, Let’s Van no será en ningún caso responsable de los daños y/o perjuicios que pudieran derivarse de dicho acceso no autorizado.</p>
        <p>Con la suscripción de los presentes Términos y Condiciones, cada Usuario declara y se obliga a defender, sacar en paz y a salvo e indemnizar a Let’s Van; así como a sus empresas matrices, controladoras, afiliadas y subsidiarias, y a sus socios, accionistas, representantes, gerentes, apoderados, funcionarios, directivos, empleados, agentes, factores, dependientes, comisionistas, mandatarios, asesores y/o prestadores de servicios, de cualesquier daños y/o perjuicios patrimoniales o morales (incluyendo, sin limitación, daños directos, daños indirectos, daños incidentales, daños especiales, daños ejemplares o punitivos, daños emergentes, lucro cesante, pérdida de datos, lesiones personales, daño a la propiedad y/o daños consecuenciales), perjuicios, gravámenes, gastos y costas, multas y/o sanciones, con adición de los honorarios razonables de abogados que tuviese que erogar Let’s Van para tal efecto, que deriven de cualesquier responsabilidades, reclamos, demandas, pleitos, litigios, requerimientos, juicios y/o procedimientos (por vía judicial o extrajudicial), motivados a instancia de las Autoridades Competentes o de cualquier tercero con interés jurídico o interés legítimo, derivados del: (i) incumplimiento por parte del Usuario de cualquier disposición contenida los presentes Términos y Condiciones o de la Normatividad Aplicable al objeto de este instrumento, (ii) incumplimiento o violación de los derechos de terceros; y (iii) incumplimiento del uso permitido de los Medios Digitales.</p>
        <p>Los Usuarios reconocen que Let’s Van no presta servicios de transporte. La prestación de los servicios de transporte en los Viajes es responsabilidad única y exclusiva de los Transportistas Independientes.</p>
        <p>Los Usuarios aceptan que Let’s Van no tiene servicios, ni convenios de conexión para abordar otros tipos de servicio de transporte terrestre y/o aéreo, por lo que el Usuario acepta toda la responsabilidad derivado de cualquier retraso o cancelación por cualquier causa, ya que Let’s Van se reserva el derecho de cambio o cancelación de horarios o rutas publicadas en su plataforma.</p>
        <p>Por lo tanto, con fundamento en el Artículo 2117 del Código Civil Federal y sus correlativos en los Códigos Civiles de las Entidades Federativas de la República Mexicana, los Usuarios renuncian expresamente al ejercicio de cualesquier acciones de responsabilidad civil, penal y/o administrativa en perjuicio de la Empresa, así como al reclamo de cualesquier daños y/o perjuicios patrimoniales o morales, incluyendo en forma meramente enunciativa daños directos, daños indirectos, daños incidentales, daños especiales, daños ejemplares o punitivos, daños emergentes, lucro cesante, pérdida de datos, lesiones personales, daño a la propiedad y/o daños consecuenciales; causados por motivo de los servicios de transporte prestados por los Transportistas Independientes.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">INDEPENDENCIA ENTRE LAS PARTES.</h4>
        <p>Para efectos del presente Contrato, los Usuarios y Let’s Van en conjunto son denominadas como las “Partes”. Las Partes reconocen que son independientes entre sí, por lo que consienten que la suscripción de los presentes Términos y Condiciones será una relación contractual de carácter mercantil, sin que dé lugar a que dicha relación se interprete como una sociedad, asociación o empresa conjunta entre ellas.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">CAUSAS DE FUERZA MAYOR.</h4>
        <p>Let’s Van no será responsable frente a los Usuarios, conforme al presente instrumento, en caso de que no puedan utilizarse los Medios Digitales o la Plataforma, o no se puedan realizar las Reservas por Causas de Fuerza Mayor, incluyendo, pero sin estar limitado a, incendios, inundaciones, huracanes, tormentas, ciclones, terremotos, sismos, movimientos telúricos, huelgas, guerras, insurrecciones, motines, rebeliones, clausuras, epidemias, pandemias, contingencias sanitarias, ataques cibernéticos de hackers, la revocación general o limitación al público usuario en el uso del software o lenguaje de programación necesario para operar los Medios Digitales, casos fortuitos u otras causas de naturaleza similar o distinta.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">CESIÓN.</h4>
        <p>Los Usuarios no podrán ceder sus derechos y obligaciones asumidos al suscribir los presentes Términos y Condiciones, sin el consentimiento previo y por escrito de un representante legal de Let’s Van. Por su parte, Let’s Van podrá ceder los presentes Términos y Condiciones a cualquier tercero sin necesidad de recabar el consentimiento previo de los Usuarios.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">NOTIFICACIONES.</h4>
        <p>La Empresa podrá realizar notificaciones al Usuario o comunicarle cualquier tipo de información a través de una notificación general en la Aplicación Móvil o en el Sitio Web, a través de un mensaje SMS o llamada telefónica a uno de los números telefónicos facilitados por el Usuario, a través de cualquier dirección de correo electrónico facilitada por los Usuarios o mediante correo tradicional dirigido a cualquier domicilio indicado por los Usuarios. El Usuario podrá notificar a la Empresa mediante el envío de un correo electrónico a la dirección prevista en el Centro de Atención y Soporte, en los horarios que sean necesarios para la prestación del servicio, es decir incluyendo las notificaciones con hasta 2 horas anticipadas al horario señalado en su boleto para la salida de su viaje, para comunicar alguna modificación operativa respecto del punto Let’s Van de partida o llegada.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">MODIFICACIONES.</h4>
        <p>Los presentes Términos y Condiciones podrán ser modificados, adicionados o reformados por Let’s Van unilateralmente y en cualquier momento. El Usuario reconoce expresamente el derecho de Let’s Van de modificar los presentes Términos y Condiciones en cualquier tiempo, debiendo el Usuario consultar periódicamente los Términos y Condiciones vigentes en cada momento.</p>
        <p>El acceso a la utilización de la Plataforma, los Medios Digitales o la Reserva de Viajes presupone la aceptación expresa y plena de los Usuarios de cualquier modificación realizada al presente documento.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">INTERPRETACIÓN Y SUBSISTENCIA.</h4>
        <p>El presente Contrato deberá interpretarse específicamente como un Contrato Mercantil, para todos los efectos legales a que haya lugar.</p>
        <p>En caso de que cualquier término, condición, sección o disposición prevista en los presentes Términos y Condiciones sea considerada o pudiera considerarse nulo, inválido, ilegal, prohibido o inexigible en cualquier jurisdicción, dicho término, condición, sección o disposición deberá separarse del presente Contrato, sin que lo anterior implique la nulidad o la invalidez de los términos o condiciones restantes. Let’s Van podrá sustituir el término, condición, sección o disposición correspondiente, de conformidad con la Normatividad Aplicable.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">VIGENCIA.</h4>
        <p>El presente instrumento tiene vigencia indefinida y será obligatorio y vinculante para los Usuarios.</p>
        <p>Los presentes Términos y Condiciones permanecerán vigentes, obligatorios y vinculantes para todos los Usuarios que hagan uso de la Plataforma, los Servicios o los Medios Digitales, o bien, para los Usuarios que tengan una Cuenta de Usuario habilitada en la Plataforma y no soliciten su baja o cancelación.</p>
        <p>En caso de que algún Usuario solicite la baja o la cancelación de su Cuenta de Usuario, permanecerán vigentes todas aquellas obligaciones devengadas, así como todas las obligaciones relacionadas con los daños, perjuicios o responsabilidades – de carácter civil, penal, administrativa o de cualquier otra índole – en que haya incurrido el Usuario en contra de los Operadores, de los Transportistas Independientes, de otros Usuarios, de Let’s Van o de cualquier tercero.</p>
    </div>
    <div class="mt-4">
        <h4 class="counter">CONTROVERSIAS.</h4>
        <p>Todas las controversias que deriven de la interpretación o el cumplimiento de los presentes Términos y Condiciones o que guarden relación con éstos, incluyendo cualquier reclamo que pudiera una de las Partes tener en contra de la otra derivado de, o relacionado con el uso de los Medios Digitales (la “Controversia”), deberán ser resueltas de acuerdo a los procedimientos descritos en esta sección, mismos que serán los únicos y exclusivos procedimientos para solucionar la Controversia, siendo aplicable para cualquier Controversia, tanto para lo adjetivo como lo sustantivo, la legislación mercantil aplicable en México, renunciando en este acto las Partes a cualquier otra legislación o jurisdicción que, por motivo de sus domicilios presentes o futuros, pudiere corresponderles.</p>
        <p>(A) Mediación</p>
        <p>Ante la existencia de una Controversia, las Partes deberán agotar el procedimiento privado de mediación en términos de la legislación aplicable en la Ciudad de México, señalando para tal efecto como mediador al mediador privado número 495 (cuatrocientos noventa y cinco) de la Ciudad de México; en el entendido de que, si por cualquier cuestión, dicha designación no fuere viable, el mediador correspondiente será designado por la Comisión de Mediación y Arbitraje Comercial de la Cámara Nacional de Comercio de la Ciudad de México (la “Comisión”).</p>
        <p>El procedimiento privado de mediación dará inicio una vez que cualquiera de las Partes notifique por escrito al mediador privado la Controversia correspondiente y se regirá, en la medida aplicable, por lo dispuesto en la Ley de Justicia Alternativa del Tribunal Superior de Justicia para el Distrito Federal, aplicable a la Ciudad de México.</p>
        <p>Será optativo para la Empresa acogerse al procedimiento privado de mediación aquí previsto o intentar su acción ante la jurisdicción ordinaria.</p>
        <p>(B) Jurisdicción Ordinaria</p>
        <p>Cualquier Controversia que no haya sido resuelta a través del procedimiento privado de mediación acordado en el párrafo (A) de la presente sección, dentro de los 40 (cuarenta) días naturales siguientes después de referido el asunto al mediador privado, o ante la determinación de la Empresa de intentar su acción directamente ante la jurisdicción ordinaria, dicha Controversia será finalmente sometida a la jurisdicción de los Juzgados y Tribunales competentes sitos en la Ciudad de México, por lo que las Partes renuncian en los términos más amplios permitidos por la Ley a cualquier otra jurisdicción que les pueda corresponder por razón de sus domicilios presentes o futuros o por cualquier otra razón o motivo.</p>
    </div>
    <hr>
</div>
@endsection